# ~/.config/hypr/hyprpaper.conf

# 1. Preload your wallpaper image into RAM (Use absolute paths)
preload = /home/user1/Pictures/wallhaven-k81776.jpg

# 2. Assign the preloaded wallpaper to your monitor(s)
# Leaving the monitor name blank applies it to ALL connected displays
wallpaper = , /home/user1/Pictures/ii8di7mmsv7h1.jpeg

# 3. Disable the default Hyprland splash rendering text
splash = false

# 4. Enable IPC if you want to change wallpapers dynamically via shell scripts
ipc = true

